/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/athletics` | `/athletics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/author` | `/author`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bell` | `/bell`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cafe` | `/cafe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calender` | `/calender`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clubs` | `/clubs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contacts` | `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/news` | `/news`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registrar` | `/registrar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/student` | `/student`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vision` | `/vision`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/athletics` | `/athletics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/author` | `/author`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bell` | `/bell`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cafe` | `/cafe`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calender` | `/calender`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/clubs` | `/clubs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/contacts` | `/contacts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/news` | `/news`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/registrar` | `/registrar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/student` | `/student`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/vision` | `/vision`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/athletics${`?${string}` | `#${string}` | ''}` | `/athletics${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/author${`?${string}` | `#${string}` | ''}` | `/author${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bell${`?${string}` | `#${string}` | ''}` | `/bell${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cafe${`?${string}` | `#${string}` | ''}` | `/cafe${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calender${`?${string}` | `#${string}` | ''}` | `/calender${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/clubs${`?${string}` | `#${string}` | ''}` | `/clubs${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/contacts${`?${string}` | `#${string}` | ''}` | `/contacts${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/news${`?${string}` | `#${string}` | ''}` | `/news${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/registrar${`?${string}` | `#${string}` | ''}` | `/registrar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/student${`?${string}` | `#${string}` | ''}` | `/student${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/vision${`?${string}` | `#${string}` | ''}` | `/vision${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/athletics` | `/athletics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/author` | `/author`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bell` | `/bell`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cafe` | `/cafe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calender` | `/calender`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clubs` | `/clubs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contacts` | `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/news` | `/news`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registrar` | `/registrar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/student` | `/student`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vision` | `/vision`; params?: Router.UnknownInputParams; };
    }
  }
}
